# build checks whether the project builds
name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        version:
            - "StableFullRelease"
            - "StableFdroidRelease"
    steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: checkout
      uses: actions/checkout@v3
    - run: ./gradlew build${{ matrix.version }} && ./gradlew clean
